name: Docker Push

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main  # 在 main 分支推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: |
        echo "Pulling Docker image from Docker Hub..."
        docker pull docker pull jeessy/ddns-go:v6.8.1-arm64

    - name: Login to Alibaba Cloud Docker Registry
      run: |
        echo "czxzj1259" | docker login --username="52088xiangzi@163.com" --password-stdin registry.cn-hangzhou.aliyuncs.com

    - name: Tag Docker Image
      run: |
        IMAGE_ID=$(docker images -q docker pull jeessy/ddns-go:v6.8.1-arm64)
        echo "Tagging image with ID: $IMAGE_ID"
        docker tag "$IMAGE_ID" registry.cn-hangzhou.aliyuncs.com/chenzx12/chenzx_hunnu:v6.8.1-arm64

    - name: Push Docker Image to Alibaba Cloud
      run: |
        echo "Pushing Docker image to Alibaba Cloud..."
        docker push registry.cn-hangzhou.aliyuncs.com/chenzx12/chenzx_hunnu:v6.8.1-arm64

    - name: Logout from Docker Registry
      run: |
        docker logout registry.cn-hangzhou.aliyuncs.com
